### ISSUE TITLE
Does not build with Node v4.0.0

### ISSUE THREAD

**Issue by jimkang** [Level/level-browserify#14]
When installing with Node v4.0.0:

    npm install --save level-browserify                     ⮂  
     
    > leveldown@1.2.2 install /Users/jimkang/gcw/toss/node_modules/level-browserify/node_modules/leveldown
    > node-pre-gyp install --fallback-to-build

      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/builder.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/db_impl.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/db_iter.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/filename.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/dbformat.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/log_reader.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/log_writer.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/memtable.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/repair.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/table_cache.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/version_edit.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/version_set.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/db/write_batch.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/helpers/memenv/memenv.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/block.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/block_builder.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/filter_block.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/format.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/iterator.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/merger.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/table.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/table_builder.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/table/two_level_iterator.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/arena.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/bloom.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/cache.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/coding.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/comparator.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/crc32c.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/env.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/filter_policy.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/hash.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/logging.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/options.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/status.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/port/port_posix.o
      CXX(target) Release/obj.target/leveldb/deps/leveldb/leveldb-1.17.0/util/env_posix.o
      LIBTOOL-STATIC Release/leveldb.a
      CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-sinksource.o
      CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy-stubs-internal.o
      CXX(target) Release/obj.target/snappy/deps/snappy/snappy-1.1.1/snappy.o
      LIBTOOL-STATIC Release/snappy.a
      CXX(target) Release/obj.target/leveldown/src/batch.o
    In file included from ../src/batch.cc:3:
    ../node_modules/nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                            ^
    ../node_modules/nan/nan.h:256:25: note: previous definition is here
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                            ^
    ../node_modules/nan/nan.h:661:13: error: no member named 'smalloc' in namespace
          'node'
        , node::smalloc::FreeCallback callback
          ~~~~~~^
    ../node_modules/nan/nan.h:672:12: error: no matching function for call to 'New'
        return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
               ^~~~~~~~~~~~~~~~~
    /Users/jimkang/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: 
          candidate function not viable: no known conversion from 'uint32_t'
          (aka 'unsigned int') to 'enum encoding' for 3rd argument
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                           ^
    /Users/jimkang/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: 
          candidate function not viable: 2nd argument ('const char *') would lose
          const qualifier
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                           ^
    /Users/jimkang/.node-gyp/4.0.0/include/node/node_buffer.h:28:40: note: 
          candidate function not viable: requires 2 arguments, but 3 were provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                           ^
    /Users/jimkang/.node-gyp/4.0.0/include/node/node_buffer.h:36:40: note: 
          candidate function not viable: requires 5 arguments, but 3 were provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                           ^
    In file included from ../src/batch.cc:3:
    ../node_modules/nan/nan.h:676:12: error: no viable conversion from
          'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
        return node::Buffer::New(v8::Isolate::GetCurrent(), size);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate
          constructor (the implicit copy constructor) not viable: no known
          conversion from 'v8::MaybeLocal<v8::Object>' to 'const
          v8::Local<v8::Object> &' for 1st argument
    class Local {
          ^
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate
          constructor (the implicit move constructor) not viable: no known
          conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&'
          for 1st argument
    class Local {
          ^
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:214:13: note: candidate
          template ignored: could not match 'Local' against 'MaybeLocal'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:326:13: note: candidate
          template ignored: could not match 'S *' against
          'v8::MaybeLocal<v8::Object>'
      V8_INLINE Local(S* that)
                ^
    In file included from ../src/batch.cc:3:
    ../node_modules/nan/nan.h:683:26: error: no member named 'Use' in namespace
          'node::Buffer'
        return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
               ~~~~~~~~~~~~~~^
    In file included from ../src/batch.cc:1:
    In file included from /Users/jimkang/.node-gyp/4.0.0/include/node/node.h:42:
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to
          'v8::Primitive *volatile' from incompatible type 'v8::Value *'
        TYPE_CHECK(T, S);
        ^~~~~~~~~~~~~~~~
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from
          macro 'TYPE_CHECK'
        *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                        ^ ~~~~~~~~~~~~~~~~~~
    ../node_modules/nan/nan.h:414:12: note: in instantiation of function template
          specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
        return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
               ^
    ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                 ^
    In file included from ../src/batch.cc:1:
    In file included from /Users/jimkang/.node-gyp/4.0.0/include/node/node.h:42:
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to
          'v8::Boolean *volatile' from incompatible type 'v8::Value *'
        TYPE_CHECK(T, S);
        ^~~~~~~~~~~~~~~~
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from
          macro 'TYPE_CHECK'
        *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                        ^ ~~~~~~~~~~~~~~~~~~
    ../node_modules/nan/nan.h:424:12: note: in instantiation of function template
          specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
        return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
               ^
    ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                 ^
    In file included from ../src/batch.cc:1:
    In file included from /Users/jimkang/.node-gyp/4.0.0/include/node/node.h:42:
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to
          'v8::Function *volatile' from incompatible type 'v8::Value *'
        TYPE_CHECK(T, S);
        ^~~~~~~~~~~~~~~~
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from
          macro 'TYPE_CHECK'
        *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                        ^ ~~~~~~~~~~~~~~~~~~
    ../node_modules/nan/nan.h:1514:12: note: in instantiation of function template
          specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
        return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
               ^
    ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                 ^
    In file included from ../src/batch.cc:1:
    In file included from /Users/jimkang/.node-gyp/4.0.0/include/node/node.h:42:
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to
          'v8::Object *volatile' from incompatible type 'v8::Value *'
        TYPE_CHECK(T, S);
        ^~~~~~~~~~~~~~~~
    /Users/jimkang/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from
          macro 'TYPE_CHECK'
        *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                        ^ ~~~~~~~~~~~~~~~~~~
    ../node_modules/nan/nan.h:1632:12: note: in instantiation of function template
          specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
        return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
               ^
    ../node_modules/nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                 ^
    9 errors generated.
    make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Darwin 14.5.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/jimkang/gcw/toss/node_modules/level-browserify/node_modules/leveldown/build-pre-gyp/leveldown.node" "--module_name=leveldown" "--module_path=/Users/jimkang/gcw/toss/node_modules/level-browserify/node_modules/leveldown/build-pre-gyp"
    gyp ERR! cwd /Users/jimkang/gcw/toss/node_modules/level-browserify/node_modules/leveldown
    gyp ERR! node -v v4.0.0
    gyp ERR! node-gyp -v v3.0.1
    gyp ERR! not ok 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jimkang/gcw/toss/node_modules/level-browserify/node_modules/leveldown/build-pre-gyp/leveldown.node --module_name=leveldown --module_path=/Users/jimkang/gcw/toss/node_modules/level-browserify/node_modules/leveldown/build-pre-gyp' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/jimkang/gcw/toss/node_modules/level-browserify/node_modules/leveldown/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    node-pre-gyp ERR! System Darwin 14.5.0
    node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/jimkang/gcw/toss/node_modules/level-browserify/node_modules/leveldown/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /Users/jimkang/gcw/toss/node_modules/level-browserify/node_modules/leveldown
    node-pre-gyp ERR! node -v v4.0.0
    node-pre-gyp ERR! node-pre-gyp -v v0.6.7
    node-pre-gyp ERR! not ok 
    Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/jimkang/gcw/toss/node_modules/level-browserify/node_modules/leveldown/build-pre-gyp/leveldown.node --module_name=leveldown --module_path=/Users/jimkang/gcw/toss/node_modules/level-browserify/node_modules/leveldown/build-pre-gyp' (1)
    npm ERR! Darwin 14.5.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "level-browserify"
    npm ERR! node v4.0.0
    npm ERR! npm  v2.14.2
    npm ERR! code ELIFECYCLE

    npm ERR! leveldown@1.2.2 install: `node-pre-gyp install --fallback-to-build`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the leveldown@1.2.2 install script 'node-pre-gyp install --fallback-to-build'.
    npm ERR! This is most likely a problem with the leveldown package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-pre-gyp install --fallback-to-build
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls leveldown
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/jimkang/gcw/toss/npm-debug.log

It installs fine with 0.12.7, though.

**Comment by jimkang** [comment]
leveldown 1.4.1 does build with v4.0.0. Maybe it's as simple as updating that?

**Comment by jimkang** [comment]
OK, PR #15 updates it, and level-browserify builds with that version of leveldown.
